### ISSUE TITLE
V3 work for 24PI2

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2220]
Continue preparing for v3 GA with continued pre-release availability, wrapping up all breaking changes by end of PI 
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2207
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2621
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2238
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2345
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2303
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2343
```
