### ISSUE TITLE
Improve experience for using API ML sessions in Zowe Explorer

### ISSUE THREAD

**Issue by t1m0thyj** [zowe/zowe-explorer-vscode#2252]
Many users of Zowe Explorer use direct-to-service profiles and store username and password as credentials.
For users of the API ML with SSO and MFA, there are enhancements we could make to provide a more first-class experience.
This epic contains issues to track related bug fixes and feature requests.
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2111
- [ ] #2210
- [ ] #2259
- [ ] #2261
- [ ] #2262
- [ ] #2263
- [ ] #2264
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2544
- [ ] #2633
- [ ] https://github.com/zowe/vscode-extension-for-zowe/issues/2682
```

**Comment by JillieBeanSim** [comment]
Adding this to 24PI2 milestone since is planned for delivery by end of 24Q2 in Roadmap.
@t1m0thyj let me know if that needs to be adjusted since I don't think all of these items are in the plan

**Comment by JillieBeanSim** [comment]
Hey @t1m0thyj with the Roadmap changing to focus on releases instead of quarters of planning, would you mind updating remaining tasks of the epic to it's planned release milestone.  If a milestone doesn't exist, like a 3.x, feel free to create one. Thanks!

**Comment by t1m0thyj** [comment]
@JillieBeanSim I've updated the milestone for the remaining issues to be V3 Prereleases for issues we plan to address before end of September and V3 GA for issues that can be addressed after V3 is released.

**Comment by JillieBeanSim** [comment]
@t1m0thyj there will be a new milestone for items after v3 GA, mainly the minor release milestones ie. v3.1.0.  v3 Prerelease should include all breaking changes and included up till last pre-release and v3 GA should include fine tuning items and non breaking change items we want included in the GA.

**Comment by JillieBeanSim** [comment]
I will keep this epic open for now and remove the milestone with delivery plan extended

**Comment by JillieBeanSim** [comment]
all tasks are complete, closing
