### ISSUE TITLE
Add integration tests using WebdriverIO

### ISSUE THREAD

**Issue by traeok** [zowe/zowe-explorer-vscode#2322]
**Is your feature request related to a problem? Please describe.**

Currently, our tests consist of unit tests and snapshots. We also have some Selenium tests for the Theia environment, but we don't have a set of integration tests for testing how the extension behaves within VS Code.

We might not be able to add these integration tests to our automated pipelines (as VS Code needs a display to show its UI), but it would help to run this locally when adding new features or addressing bugs to make sure that all features work as intended.

**Describe the solution you'd like**

Leverage the [WebdriverIO](https://webdriver.io) framework to create a preliminary set of integration tests for Zowe Explorer.

**Describe alternatives you've considered**

I'm not aware of other frameworks for testing the user interface for VS Code extensions, but if an alternative exists, we should compare our options and pick the best framework for our use cases.

```[tasklist]
### Tasks
- [x] Click on the Zowe Explorer icon
- [x] Collapse and expand the favorites node in each tree view
- [x] Click the "+" button to open the "Add Profile/Config" quick pick
- [x] Toggle on/off tree views in Zowe Explorer pane
- [x] Configure Zowe Explorer in extension settings (section is visible)
- [x] "Edit Team Configuration File" option opens editor with config
- [x] Issue a TSO command through the Command Palette
- [x] Issue a MVS command through the Command Palette
- [x] Issue a Unix command through the Command Palette
- [x] Select multiple tree items without it breaking the selection (might be a VS Code issue)
- [x] Add profile to a single tree view
- [x] Add profile to all tree views
- [x] Expand and collapse a profile in each tree - verified
- [x] Expand and collapse a profile in each tree - unverified/no filter set
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2993
- [x] User can add a filter search on a session node in each tree
- [x] User can select an existing filter search in each tree
- [x] Data set can be opened in tree, edited, and saved
- [x] Favorited data set can be opened in tree, edited, and saved
- [x] Favorited PDS member can be opened in tree, edited, and saved
- [x] USS file can be opened in tree view, edited and saved
- [x] User can expand a USS directory in the tree view and select one of its files
- [x] User can expand a PDS in the tree view and select one of its members
- [x] PDS member can be opened in tree, edited, and saved
```

**Comment by JTonda** [comment]
Test Plan:
- Set up framework
- Duplicate/model Thea tests - initial set of tests (not all inclusive)
- Add to PR checklist

**Comment by traeok** [comment]
Here are the branches I've created for my research - each branch contains a sample test that uses the given framework.

WebdriverIO: https://github.com/zowe/zowe-explorer-vscode/tree/test/wdio
ExTester: https://github.com/zowe/zowe-explorer-vscode/tree/test/ExTester
Nightwatch.js: https://github.com/zowe/zowe-explorer-vscode/tree/test/Nightwatch.js
