### ISSUE TITLE
24PI2 Planning

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2799]
# Zowe Explorer Squad - 24PI2 - (2024/04/23 - 2024/07/22)

### Planning 2024/04/23 - 2024/04/26

[Kickoff](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=2301895&calstart=2024-04-16) - 04/16/2024 - 9:00 - 10:30 am ET
 [Opening (Day 1)](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=2301737&calstart=2024-04-24) - 04/24/2024 8:00 - 11:00 am ET
Thursday, April 25 - [Breakouts](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=2309477&calstart=2024-04-24) (Optional) (Day 2)
[Final Readouts (Day 3)](https://lists.openmainframeproject.org/g/zowe-dev/viewevent?eventid=2301738&calstart=2024-04-26) - 04/26/2024 9:00 - 11:00 am ET

### Releases

- 2.16.0 - May 13, 2024
- 2.17.0 - July 15, 2024
- 2.18.0 - Aug 26, 2024
- 3.0.0 - Sep 30, 2024

### Continue preparing for v3 GA with continued pre-release availability, wrapping up all breaking changes by end of PI.

- https://github.com/zowe/vscode-extension-for-zowe/issues/2621 - (24Q1 rollover)
- https://github.com/zowe/vscode-extension-for-zowe/issues/2373 - (24Q1 rollover)
- https://github.com/zowe/zowe-explorer-vscode/issues/2238 - **Breaking change**
- https://github.com/zowe/zowe-explorer-vscode/issues/2345  - **Breaking change**
- https://github.com/zowe/zowe-explorer-vscode/issues/2303 - **Breaking change**
- https://github.com/zowe/zowe-explorer-vscode/issues/2622
- https://github.com/zowe/zowe-explorer-vscode/issues/2546
- https://github.com/zowe/zowe-explorer-vscode/issues/2322
- https://github.com/zowe/vscode-extension-for-zowe/issues/2264 - *stretch* (24Q1 rollover)
- https://github.com/zowe/zowe-explorer-vscode/issues/2265 - *stretch*
- https://github.com/zowe/zowe-explorer-vscode/issues/2258 - *stretch*
- https://github.com/zowe/zowe-explorer-vscode/issues/449 - *stretch*

###  Please users and extenders with continuous development of enhancements for upcoming v2.x releases.

- https://github.com/zowe/vscode-extension-for-zowe/issues/2590 - *in progress* (24Q1 rollover)
- https://github.com/zowe/zowe-explorer-vscode/issues/2386 - moving to [v3.0.0 GA Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3005)
- https://github.com/zowe/zowe-explorer-vscode/issues/2271 - *stretch*
- https://github.com/zowe/zowe-explorer-vscode/issues/2252  - *stretch* 

### Reduce Zowe Explorer reported bug count by 20% by the end of the PI. (82 total bugs in repo as of 4/8/2024)

- https://github.com/zowe/vscode-extension-for-zowe/issues/2561 - (24Q1 rollover)
- https://github.com/zowe/zowe-explorer-vscode/issues/2798 
- https://github.com/zowe/zowe-explorer-vscode/issues/2627 - moving to [v2.18.0 Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3006)
- https://github.com/zowe/zowe-explorer-vscode/issues/2406 - moving to [v2.18.0 Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3006)
- https://github.com/zowe/zowe-explorer-vscode/issues/2800
- https://github.com/zowe/zowe-explorer-vscode/issues/2465  
- https://github.com/zowe/zowe-explorer-vscode/issues/2337 - moving to [v2.18.0 Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3006)  
- https://github.com/zowe/zowe-explorer-vscode/issues/2327
- https://github.com/zowe/zowe-explorer-vscode/issues/2825
- https://github.com/zowe/zowe-explorer-vscode/issues/2294
- https://github.com/zowe/zowe-explorer-vscode/issues/2796
- https://github.com/zowe/zowe-explorer-vscode/issues/2823
- https://github.com/zowe/zowe-explorer-vscode/issues/2618 - *stretch*
- https://github.com/zowe/zowe-explorer-vscode/issues/2528 - moving to [v2.18.0 Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3006)
- https://github.com/zowe/zowe-explorer-vscode/issues/1865 - *stretch*

### CICS Related Issues (STRETCH)

- https://github.com/zowe/cics-for-zowe-client/issues/61 - *stretch*
- https://github.com/zowe/cics-for-zowe-client/issues/118 - *stretch*

### [Add more functionality to the Jobs tree view](https://github.com/zowe/vscode-extension-for-zowe/issues/1597)

**COMPLETED**

- *What problem are you solving?*
  - Users would like a comparable experience working with JES files, Zowe Explorer doesn't have a lot of functionality in that tree compared to others.
- *What are you doing to solve it?*
  - Add more functionality to jobs in the tree, ie. local sorting, filtering, and more.
- *When do you plan to start the work?*
  - 23Q1
- *When do you plan to deliver the solution?*
  - 24Q1

### [Zowe Explorer v3 GA]()

- *What problem are you solving?*
  -  We have a great deal of items to complete for the v3 GA date and we don't want to miss anything important.
- *What are you doing to solve it?
  - Prepare a plan for dependency & engine updates, enhancements, migration tactics, and other items needed for our v3 GA release.
- *When do you plan to start the work?*
  - The work has been in progress since 23Q1
- *When do you plan to deliver the solution?*
  - ?

### [Improve experience for using API ML sessions in Zowe Explorer](https://github.com/zowe/vscode-extension-for-zowe/issues/2252)

- *What problem are you solving?*
  - Many users of Zowe Explorer aren't familiar with or are unaware of authentication methods supported by Zowe Explorer, like token authentication, SSO, & MFA. 
- *What are you doing to solve it?
  - For users of the API ML with SSO and MFA, there are enhancements we could make to provide a more first-class experience.
- *When do you plan to start the work?*
  - 23Q3
- *When do you plan to deliver the solution?*
  - 24Q2

```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2836
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2835
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2220
```

**Comment by JillieBeanSim** [comment]
## Sprint dates

Sprint 1 - 2024/04/30 - 2024/05/13 (Innovation Sprint)
Sprint 2 - 2024/05/14 - 2024/05/27
Sprint 3 - 2024/05/28 - 2024/06/10
Sprint 4 - 2024/06/11 - 2024/06/24
Sprint 5 - 2024/06/25 - 2024/07/08
Sprint 6 - 2024/07/09 - 2024/07/22

**Comment by adam-wolfe** [comment]
Great list, we should also consider (possibly as stretches):
- https://github.com/zowe/zowe-explorer-vscode/issues/2258
- https://github.com/zowe/zowe-explorer-vscode/issues/449

**Comment by JillieBeanSim** [comment]
Possible new Roadmap items for discussion, can be delivered late in the year early next year:
- #497 
  - has 2 open issues that may be solved by the new tree provider work.
- #2781 
- #2793

**Comment by JillieBeanSim** [comment]
@zFernand0 do we want any CICS items added to plan?

**Comment by JillieBeanSim** [comment]
> Great list, we should also consider (possibly as stretches):
> 
> * [Tabular display option for Jobs tree #2258](https://github.com/zowe/zowe-explorer-vscode/issues/2258)
> * [Full text search across all the members, like ISPF SrchFor utility does #449](https://github.com/zowe/zowe-explorer-vscode/issues/449)

@adam-wolfe added as stretch to v3 objective, these items can easily be delivered after GA but thinking big wow enhancements should be v3 now with closing timeline to bring customers over once GA.

**Comment by adam-wolfe** [comment]
> > Great list, we should also consider (possibly as stretches):
> > 
> > * [Tabular display option for Jobs tree #2258](https://github.com/zowe/zowe-explorer-vscode/issues/2258)
> > * [Full text search across all the members, like ISPF SrchFor utility does #449](https://github.com/zowe/zowe-explorer-vscode/issues/449)
> 
> @adam-wolfe added as stretch to v3 objective, these items can easily be delivered after GA but thinking big wow enhancements should be v3 now with closing timeline to bring customers over once GA.

Totally agree.

**Comment by adam-wolfe** [comment]
I think we will also want to include https://github.com/zowe/zowe-explorer-vscode/issues/2322

**Comment by JillieBeanSim** [comment]
added @adam-wolfe 
also updated community ZE planning [page](https://github.com/zowe/community/blob/master/Project%20Management/PI%20Planning/24PI2%20Planning/PI%20Planning%20Preparation%20by%20Squad/Zowe%20Explorer%20Squad%20-%2024PI2%20Objectives.md)

**Comment by zFernand0** [comment]
> zFernand0 do we want any CICS items added to plan?

Hey @JillieBeanSim,
There are [a few epics](https://github.com/zowe/cics-for-zowe-client/issues?q=is%3Aissue+is%3Aopen+label%3AEpic) created in the CICS monorepo, but I do not believe we should commit to any of them for the time being.

If we want to commit to any CICS related work, I say we focus on reducing the number of [open bugs in the monorepo](https://github.com/zowe/cics-for-zowe-client/issues?q=is%3Aopen+is%3Aissue+label%3Abug). Here are some of the ones I consider most relevant:
- https://github.com/zowe/cics-for-zowe-client/issues/61
- https://github.com/zowe/cics-for-zowe-client/issues/118
- https://github.com/zowe/cics-for-zowe-client/issues/108 - _v1: security_
- https://github.com/zowe/cics-for-zowe-client/issues/107 - _v1: stretch_

Finally, there are some [high priority enhancements](https://github.com/zowe/cics-for-zowe-client/issues?q=is%3Aissue+is%3Aopen+label%3Apriority-high) that we could have as stretch items here.
- https://github.com/zowe/cics-for-zowe-client/issues/33 - _stretch_
- https://github.com/zowe/cics-for-zowe-client/issues/42 - _stretch_

**Note:** All issues listed above are in the priority that I believe will be most impactful to end users 😋

**Comment by adam-wolfe** [comment]
It may be worth also considering #2252 for the PI plan.

**Comment by JillieBeanSim** [comment]
Hey @adam-wolfe thanks for putting the chart together, it seems to be the same information just broken down to show all the lowest level within a chart which is good for our wiki to give an in-depth view.  With the GH Roadmap being tabular and able to step into each level easily within a GUI it may be ok to just update the Epics to reflect the Theme with description being the problem statement keeping the checklist of items to be worked on.  What do you think?

**Comment by adam-wolfe** [comment]
Sounds good to me 👍

**Comment by JillieBeanSim** [comment]
closing plan for 24PI3 plan items [v2.18.0 Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3006) & [v3.0.0 GA Release Plan](https://github.com/zowe/zowe-explorer-vscode/issues/3005)
