### ISSUE TITLE
24PI2 bug reduction of 20%

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#2836]
Reduce Zowe Explorer reported bug count by 20% by the end of the PI. (82 total bugs in repo as of 4/8/2024)
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2544
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2561
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2800
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2618
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2465
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2327
```
