### ISSUE TITLE
v3.0.0 GA Release Plan

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3005]
Plan prepared for inclusion in v3.0 GA
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2762
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2938
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2862
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2901
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2763
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2719
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3007
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2906
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2264
```
