### ISSUE TITLE
v3.0.1 Release Plan

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3165]
items to include in the patch release:

```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3125
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3150
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3163
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3168
```
