### ISSUE TITLE
v3.1.0 Release Plan

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3166]
List of items to include in 3.1.0 release:

```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3037
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2935
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3010
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3071
- [x] https://github.com/zowe/zowe-explorer-vscode/issues/449
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/1941
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3047
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3381
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3355
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3324
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3180
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3197
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3265
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3175
```

**Comment by JillieBeanSim** [comment]
With us now being in code freeze the following items above will be moved to 3.2 milestone/plan
- https://github.com/zowe/zowe-explorer-vscode/issues/2939
- https://github.com/zowe/zowe-explorer-vscode/issues/2386
- https://github.com/zowe/zowe-explorer-vscode/issues/2373
- https://github.com/zowe/zowe-explorer-vscode/issues/2978
