### ISSUE TITLE
Epic: Integrated Terminals (iTerm) - Early feedback

### ISSUE THREAD

**Issue by zFernand0** [zowe/zowe-explorer-vscode#3203]
**Is your feature request related to a problem? Please describe.**

This is just an epic to capture the early feedback received on a system demo shortly before the Zowe V3 GA date.

WIP
---

- [ ] iTerm(context): Handle TSO prompts with integrated TSO terminals
- [ ] iTerm(context): Enable USS path navigation from integrated Unix terminals
- [ ] iTerm(special): Handle asynchronous operations (delayed response | submit & forget)
- [ ] iTerm(special): Introduce a response timeout configurable per command
- [ ] iTerm(special): Allow to switch profiles from an existing iTerm
- [ ] iTerm(special): Allow panel-location arrangement (side-by-side, full-screen)
- [ ] iTerm(config): Handle iTerm specific configurations (default response timeout)
- [ ] iTerm(config): Add config for default response timeout
- [ ] iTerm(config): Add config for default dimensions and/or panel-location
- [ ] iTerm(config): Enable or disable the saving of command history
- [ ] iTerm(history): Allow normal webview operations (refresh, clear all, delete)
- [ ] iTerm(history): Add a copy-to-cpliboard button for a command
- [ ] iTerm(UX): Add auto-completion features
- [ ] iTerm(UX): Add help for common commands
- [ ] iTerm(UX): Add a `Did you mean?` helper for common commands 

Legend:
- iTerm: Alias for "_**Integrated Terminal**_"
- `(context)`: Refers to issues where the iTerm needs to be context aware
- `(special)`: Refers to  issues that may require special keyboard modifiers (ctrl, alt) or special commands (`:clear`, `:exit`)
- `(config)`: Refers to issues regarding iTerm user configurable settings
- `(history)`: Refers to issues related to handling command history (via webviews) 
- `(UX)`: Refers to issues regarding the user experience of the iTerms

**Comment by JillieBeanSim** [comment]
Hey @zFernand0 this is a huge epic 😄 thanks for gathering the feedback into one place.

We should discuss if we want to add this to the Roadmap for this year or if you think it may take longer.

FYI @adam-wolfe

**Comment by JWaters02** [comment]
Hi @zFernand0

**Comment by zFernand0** [comment]
> Not sure if this is already covered in one of your sub issues, but there is a bug in the USS terminal where running programs (e.g. python program) that produce output where the outputs do not show in the terminal, ctrl + c doesn't do anything and the terminal has to be killed.

I'm afraid that's not captured! 🙏 
Thanks for sharing! We should probably open it as a bug and add it here 🙏

**Comment by JWaters02** [comment]
No problem, I'll add that as a bug report, thanks!

**Comment by zFernand0** [comment]
> FYI I created it as a sub issue because of this warning. I suppose you should probably switch your task list to do the same (explained in that doc it links to).
> 

Good catch! 🥳 
All done! 🙏
