### ISSUE TITLE
v3.0.2 release plan

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3227]
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/2983
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3249
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3246
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3239
```
