### ISSUE TITLE
v3.0.3 Release Plan

### ISSUE THREAD

**Issue by JillieBeanSim** [zowe/zowe-explorer-vscode#3250]
plannned items for upcoming patch release:
```[tasklist]
### Tasks
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3201
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3260
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3261
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3252
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3255
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3273
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3274
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3142
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3275
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3267
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3268
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3280
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3281
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3225
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3292
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3290
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3297
- [ ] https://github.com/zowe/zowe-explorer-vscode/issues/3278
- [ ] https://github.com/zowe/zowe-explorer-vscode/pull/3279
```
